---
- name: Install Jenkins
  hosts: jenkins
  become: true


  tasks:
    - name: Check Hostname
      command: hostname

    - name: APT Update
      command: apt update

    - name: Install Java
      command: apt install -y openjdk-17-jre

    - name: Install key for the Jenkins apt repository
      apt_key:
        url: "https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key"
        state: present

    - name: Install access to the Jenkins apt repository
      apt_repository:
        repo: deb http://pkg.jenkins.io/debian-stable binary/
        state: present
        filename: 'jenkins-stable'

    - name: APT Update for the Jenkins repository
      command: apt update

    - name: Install Jenkins package
      apt:
        name: jenkins
        state: present

    - name: Wait for Jenkins to start up
      wait_for: timeout=35

    - name: Get Jenkins password
      shell: cat /var/lib/jenkins/secrets/initialAdminPassword
      changed_when: false
      register: result

    - name: Password to "Unlock Jenkins"
      debug:
        var: result.stdout
