---
- name: Install webserver
  hosts: host2
  become: yes

  tasks:

    - name: update
      apt: update_cache=yes

    - name: Install Nginx
      apt: name=nginx state=latest

      notify:
        - restart nginx

    - name: Copy Site
      copy:
        src: /home/pxilips/ansible/website2/index.html
        dest: /var/www/html/index.html

  handlers:
    - name: restart nginx
      service: name=nginx state=reloaded